# Generated by Django 3.0.5 on 2024-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightenapp', '0004_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
